"""Create chats table

Revision ID: 099bf7550911
Revises: f5218b80f531
Create Date: 2023-05-17 23:18:34.522695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099bf7550911'
down_revision = 'f5218b80f531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key('chats_users_fk', source_table="chats", referent_table="chats", local_cols=[
                          'owner_id'], remote_cols=['id'], ondelete="CASCADE")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_users_fk', table_name="chats")
    op.drop_column('chats', 'owner_id')
    pass
    # ### end Alembic commands ###
