"""Modify completion field to accept unlimited characters

Revision ID: b239ff6c6c65
Revises: f5218b80f531
Create Date: 2023-05-18 12:07:41.341601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b239ff6c6c65'
down_revision = 'f5218b80f531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('chats', 'completion', existing_type=sa.String(length=255), type_=sa.Text())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
